sign = "Auto Reload --- "
reloaded = " found modified, reloaded"
missing = " found missing"
timer_start = sign + "Reload datas timer started"
timer_end = sign + "Reload datas timer ended"
handler = sign + "All files modification time updated"
no_modif = sign + "No modified files found"